version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: password
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=password
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=external
      - N8N_RUNNERS_AUTH_TOKEN=super_secret_token
      - N8N_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0
      - GENERIC_TIMEZONE=Europe/Prague
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres

  n8n-runner:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    entrypoint: ["/bin/sh", "-c", "/usr/local/bin/task-runner-launcher javascript;"]
    environment:
      - N8N_RUNNERS_AUTH_TOKEN=super_secret_token
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n:5679
      - N8N_RUNNERS_MAX_CONCURRENCY=5
      - N8N_RUNNERS_AUTO_SHUTDOWN_TIMEOUT=15
      - NODE_OPTIONS=--max-old-space-size=512
      - GENERIC_TIMEZONE=Europe/Prague
    depends_on:
      - n8n
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5680/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  n8n_data:
  postgres_data:

