[project]
name = "10-lekcia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=1.24.0",
    "matplotlib>=3.7.0",
    "gymnasium>=0.28.0",
    "torch>=2.0.0",
    "gym>=0.26.2",
]
